#!/usr/bin/env ruby

=begin
ARGV.length.times do |i|
	if ARGV[i] == "--pattern" or ARGV[i] == "-p"
		pattern = ARGV[i+1]
	elsif ARGV[i] == "--charset" or ARGV[i] == "-c"
		charset = ARGV[i+1]
	elsif ARGV[i] == "--fileName" or ARGV[i] == "-o"
		fileName = ARGV[i+1]
	elsif ARGV[i] == "--help" or ARGV[i] == "-h"
		DictionaryProcesses.helpMenu
	end
end


#puts "tamamdır" if "5" =~ /\A[0-9]\z/
#puts "tamamdır" if "*" =~ /\A[0-9]\z/


excepting = []
specificIndex = []
asteriskIndex = []
count = 0
=end

#arr = "1*1*1".split('')


=begin
"1*8**3".chars do |c| 
	if c =~ /[0-9]/
		excepting.push(c)  # Tekrarlanmayı önlemek için depolanır.
		specificIndex.push(count)
	else
		asteriskIndex.push(count)	# Yıldızlar tespit edilir.
	end

	count += 1
end
=end

arr = "****".split('')

file = File.open("deneme.txt", "w")


if arr.length == 1
	raise "\n\n########################################\n\nBöyle pattern olmaz olum! Bunun için pattern'a ihtiyacın yok.\n\n########################################\n\n"
elsif arr.length == 2
	if arr[0] == '*' and arr[1] == '*'
		raise "\n\n########################################\n\nBöyle pattern olmaz olum! Bunun için pattern'a ihtiyacın yok.\n\n########################################\n\n"
	elsif arr[0] == '*' and arr[1] != '*'
		(0..9).each do |i|
			file.puts i.to_s + arr[1].to_s
		end
	elsif arr[0] != '*' and arr[1] == '*'
		(0..9).each do |i|
			file.puts arr[0].to_s + i.to_s
		end
	elsif arr[0] != '*' and arr[1] != '*'
		raise "\n\n########################################\n\nBöyle pattern olmaz olum! Bunun için pattern'a ihtiyacın yok.\n\n########################################\n\n"
	end
elsif arr.length == 3
	if arr[0] == '*' and arr[1] == '*' and arr[2] == '*'
		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts i.to_s + j.to_s + k.to_s
				end
			end
		end
	elsif arr[0] == '*' and arr[1] == '*' and arr[2] != '*'
		(0..9).each do |i|
			(0..9).each do |j|
				file.puts i.to_s + j.to_s + arr[2].to_s
			end
		end
	elsif arr[0] == '*' and arr[1] != '*' and arr[2] == '*'
		(0..9).each do |i|
			(0..9).each do |j|
				file.puts i.to_s arr[1].to_s + j.to_s
			end
		end
	elsif arr[0] == '*' and arr[1] != '*' and arr[2] != '*'
		(0..9).each do |i|
			file.puts i.to_s arr[1].to_s + arr[2].to_s
		end
	elsif arr[0] != '*' and arr[1] == '*' and arr[2] == '*'
		(0..9).each do |i|
			(0..9).each do |j|
				file.puts arr[0].to_s + i.to_s + j.to_s
			end
		end
	elsif arr[0] != '*' and arr[1] == '*' and arr[2] != '*'
		(0..9).each do |i|
			file.puts arr[0].to_s + i.to_s + arr[2].to_s
		end
	elsif arr[0] != '*' and arr[1] != '*' and arr[2] == '*'
		(0..9).each do |i|
			file.puts arr[0].to_s + arr[1].to_s + i.to_s
		end
	elsif arr[0] != '*' and arr[1] != '*' and arr[2] != '*'
		raise "\n\n########################################\n\nBöyle pattern olmaz olum! Bunun için pattern'a ihtiyacın yok.\n\n########################################\n\n"
	end
elsif arr.length == 4
	if arr[0] == '*' and arr[1] == '*' and arr[2] == '*' and arr[3] == '*'
		raise "\n\n########################################\n\nBöyle pattern olmaz olum! Bunun için pattern'a ihtiyacın yok.\n\n########################################\n\n"
	
	elsif arr[0] == '*' and arr[1] == '*' and arr[2] == '*' and arr[3] != '*'
		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts i.to_s + j.to_s + k.to_s + arr[3].to_s
				end
			end
		end
	elsif arr[0] == '*' and arr[1] == '*' and arr[2] != '*' and arr[3] == '*'
		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts i.to_s + j.to_s + arr[2].to_s + k.to_s
				end
			end
		end
	elsif arr[0] == '*' and arr[1] == '*' and arr[2] != '*' and arr[3] != '*'
		(0..9).each do |i|
			(0..9).each do |j|
				file.puts i.to_s + j.to_s + arr[2].to_s + arr[3].to_s
			end
		end
	elsif arr[0] == '*' and arr[1] != '*' and arr[2] == '*' and arr[3] == '*'
		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts i.to_s + arr[1].to_s + j.to_s + k.to_s
				end
			end
		end
	elsif arr[0] == '*' and arr[1] != '*' and arr[2] == '*' and arr[3] != '*'
		(0..9).each do |i|
			(0..9).each do |j|
				file.puts i.to_s + arr[1].to_s + j.to_s + arr[3].to_s
			end
		end
	elsif arr[0] == '*' and arr[1] != '*' and arr[2] != '*' and arr[3] == '*'
		(0..9).each do |i|
			(0..9).each do |j|
				file.puts i.to_s + arr[1].to_s + arr[2].to_s + j.to_s
			end
		end
	elsif arr[0] == '*' and arr[1] != '*' and arr[2] != '*' and arr[3] != '*'
		(0..9).each do |i|
			file.puts i.to_s + arr[1].to_s + arr[2].to_s + arr[3].to_s
		end
	elsif arr[0] != '*' and arr[1] == '*' and arr[2] == '*' and arr[3] == '*'
		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts arr[0].to_s + i.to_s + j.to_s + k.to_s
				end
			end
		end
	elsif arr[0] != '*' and arr[1] == '*' and arr[2] == '*' and arr[3] != '*'
		(0..9).each do |i|
			(0..9).each do |j|
				file.puts arr[0].to_s + i.to_s + j.to_s + arr[3].to_s
			end
		end
	elsif arr[0] != '*' and arr[1] == '*' and arr[2] != '*' and arr[3] == '*'
		(0..9).each do |i|
			(0..9).each do |j|
				file.puts arr[0].to_s + i.to_s + arr[2].to_s + j.to_s
			end
		end
	elsif arr[0] != '*' and arr[1] == '*' and arr[2] != '*' and arr[3] != '*'
		(0..9).each do |i|
			file.puts arr[0].to_s + i.to_s + arr[2].to_s + arr[3].to_s	
		end
	elsif arr[0] != '*' and arr[1] != '*' and arr[2] == '*' and arr[3] == '*'
		(0..9).each do |i|
			(0..9).each do |j|
				file.puts arr[0].to_s + arr[1].to_s + i.to_s + j.to_s
			end
		end
	elsif arr[0] != '*' and arr[1] != '*' and arr[2] == '*' and arr[3] != '*'
		(0..9).each do |i|
			file.puts arr[0].to_s + arr[1].to_s + i.to_s + arr[3].to_s
		end
	elsif arr[0] != '*' and arr[1] != '*' and arr[2] != '*' and arr[3] == '*'
		(0..9).each do |i|
			file.puts arr[0].to_s + arr[1].to_s + arr[2].to_s + i.to_s
		end
	elsif arr[0] != '*' and arr[1] != '*' and arr[2] != '*' and arr[3] != '*'
		raise "\n\n########################################\n\nBöyle pattern olmaz olum! Bunun için pattern'a ihtiyacın yok.\n\n########################################\n\n"
	end

elsif arr.length == 5
	if arr[0] == '*' and arr[1] == '*' and arr[2] == '*' and arr[3] == '*' and arr[4] == '*'
		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					(0..9).each do |x|
						(0..9).each do |y|
							file.puts i.to_s + j.to_s + k.to_s + x.to_s + y.to_s
						end
					end
				end
			end
		end

	elsif arr[0] == '*' and arr[1] == '*' and arr[2] == '*' and arr[3] == '*' and arr[4] != '*'
		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					(0..9).each do |x|
						file.puts i.to_s + j.to_s + k.to_s + x.to_s + arr[4].to_s
					end
				end
			end
		end


	elsif arr[0] == '*' and arr[1] == '*' and arr[2] == '*' and arr[3] != '*' and arr[4] == '*'

		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					(0..9).each do |x|
						file.puts i.to_s + j.to_s + k.to_s + arr[3].to_s + x.to_s 
					end
				end
			end
		end

	elsif arr[0] == '*' and arr[1] == '*' and arr[2] == '*' and arr[3] != '*' and arr[4] != '*'

		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts i.to_s + j.to_s + k.to_s + arr[3].to_s + arr[4].to_s
				end
			end
		end

	elsif arr[0] == '*' and arr[1] == '*' and arr[2] != '*' and arr[3] == '*' and arr[4] == '*'
		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					(0..9).each do |x|
						file.puts i.to_s + j.to_s + arr[2].to_s + k.to_s + x.to_s 
					end
				end
			end
		end

	elsif arr[0] == '*' and arr[1] == '*' and arr[2] != '*' and arr[3] == '*' and arr[4] != '*'

		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts i.to_s + j.to_s + arr[2].to_s + k.to_s + arr[4].to_s
				end
			end
		end


	elsif arr[0] == '*' and arr[1] == '*' and arr[2] != '*' and arr[3] != '*' and arr[4] == '*'
		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts i.to_s + j.to_s + arr[2].to_s + arr[3].to_s + k.to_s
				end
			end
		end

	elsif arr[0] == '*' and arr[1] == '*' and arr[2] != '*' and arr[3] != '*' and arr[4] != '*'

		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts i.to_s + j.to_s + arr[2].to_s + arr[3].to_s + arr[4].to_s
				end
			end
		end

	elsif arr[0] == '*' and arr[1] != '*' and arr[2] == '*' and arr[3] == '*' and arr[4] == '*'

		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					(0..9).each do |l|
						file.puts i.to_s + arr[1].to_s + j.to_s + k.to_s + l.to_s
					end
				end
			end
		end


	elsif arr[0] == '*' and arr[1] != '*' and arr[2] == '*' and arr[3] == '*' and arr[4] != '*'

		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts i.to_s + arr[1].to_s + j.to_s + k.to_s + arr[4].to_s
				end
			end
		end


	elsif arr[0] == '*' and arr[1] != '*' and arr[2] == '*' and arr[3] != '*' and arr[4] == '*'

		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts i.to_s + arr[1].to_s + j.to_s + arr[3].to_s + k.to_s
				end
			end
		end

	elsif arr[0] == '*' and arr[1] != '*' and arr[2] == '*' and arr[3] != '*' and arr[4] != '*'

		(0..9).each do |i|
			(0..9).each do |j|
				file.puts i.to_s + arr[1].to_s + j.to_s + arr[3].to_s + arr[4].to_s	
			end
		end

	elsif arr[0] == '*' and arr[1] != '*' and arr[2] != '*' and arr[3] == '*' and arr[4] == '*'

		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts i.to_s + arr[1].to_s + arr[2].to_s + j.to_s + k.to_s	
				end
			end
		end


	elsif arr[0] == '*' and arr[1] != '*' and arr[2] != '*' and arr[3] == '*' and arr[4] != '*'

		(0..9).each do |i|
			(0..9).each do |j|
				file.puts i.to_s + arr[1].to_s + arr[2].to_s + j.to_s + arr[4].to_s
			end
		end

	elsif arr[0] == '*' and arr[1] != '*' and arr[2] != '*' and arr[3] != '*' and arr[4] == '*'

		(0..9).each do |i|
			(0..9).each do |j|
				file.puts i.to_s + arr[1].to_s + arr[2].to_s + arr[3].to_s + j.to_s
			end
		end

	elsif arr[0] == '*' and arr[1] != '*' and arr[2] != '*' and arr[3] != '*' and arr[4] != '*'

		(0..9).each do |i|
			(0..9).each do |j|
				file.puts i.to_s + arr[1].to_s + arr[2].to_s + arr[3].to_s + arr[4].to_s
			end
		end

	elsif arr[0] != '*' and arr[1] == '*' and arr[2] == '*' and arr[3] == '*' and arr[4] == '*'

		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					(0..9).each do |x|
						file.puts arr[0].to_s + i.to_s + j.to_s + k.to_s + x.to_s
					end
				end
			end
		end

	elsif arr[0] != '*' and arr[1] == '*' and arr[2] == '*' and arr[3] == '*' and arr[4] != '*'

		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts arr[0].to_s + i.to_s + j.to_s + k.to_s + arr[4].to_s
				end
			end
		end

	elsif arr[0] != '*' and arr[1] == '*' and arr[2] == '*' and arr[3] != '*' and arr[4] == '*'

		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts arr[0].to_s + i.to_s + j.to_s + arr[3].to_s + k.to_s
				end
			end
		end


	elsif arr[0] != '*' and arr[1] == '*' and arr[2] == '*' and arr[3] != '*' and arr[4] != '*'

		(0..9).each do |i|
			(0..9).each do |j|
				file.puts arr[0].to_s + i.to_s + j.to_s + arr[3].to_s + arr[4].to_s
			end
		end

	elsif arr[0] != '*' and arr[1] == '*' and arr[2] != '*' and arr[3] == '*' and arr[4] == '*'

		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts arr[0].to_s + i.to_s + arr[2].to_s + j.to_s + k.to_s
				end
			end
		end


	elsif arr[0] != '*' and arr[1] == '*' and arr[2] != '*' and arr[3] == '*' and arr[4] != '*'

		(0..9).each do |i|
			(0..9).each do |j|
				file.puts arr[0].to_s + i.to_s + arr[2].to_s + j.to_s + arr[4].to_s
			end
		end

	elsif arr[0] != '*' and arr[1] == '*' and arr[2] != '*' and arr[3] != '*' and arr[4] == '*'

		(0..9).each do |i|
			(0..9).each do |j|
				file.puts arr[0].to_s + i.to_s + arr[2].to_s + arr[3].to_s + j.to_s	
			end
		end

	elsif arr[0] != '*' and arr[1] == '*' and arr[2] != '*' and arr[3] != '*' and arr[4] != '*'

		(0..9).each do |i|
			file.puts arr[0].to_s + i.to_s + arr[2].to_s + arr[3].to_s + arr[4].to_s	
		end	

	elsif arr[0] != '*' and arr[1] != '*' and arr[2] == '*' and arr[3] == '*' and arr[4] == '*'

		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts arr[0].to_s + arr[1].to_s + i.to_s + j.to_s + k.to_s	
				end
			end
		end

	elsif arr[0] != '*' and arr[1] != '*' and arr[2] == '*' and arr[3] == '*' and arr[4] != '*'

		(0..9).each do |i|
			(0..9).each do |j|
				file.puts arr[0].to_s + arr[1].to_s + i.to_s + j.to_s + arr[4].to_s	
			end
		end

	elsif arr[0] != '*' and arr[1] != '*' and arr[2] == '*' and arr[3] != '*' and arr[4] == '*'

		(0..9).each do |i|
			(0..9).each do |j|
				(0..9).each do |k|
					file.puts arr[0].to_s + arr[1].to_s + i.to_s + arr[3].to_s + k.to_s	
				end
			end
		end

	elsif arr[0] != '*' and arr[1] != '*' and arr[2] == '*' and arr[3] != '*' and arr[4] != '*'

		(0..9).each do |i|
			file.puts arr[0].to_s + arr[1].to_s + i.to_s + arr[3].to_s + arr[4].to_s	
		end

	elsif arr[0] != '*' and arr[1] != '*' and arr[2] != '*' and arr[3] == '*' and arr[4] == '*'

		(0..9).each do |i|
			(0..9).each do |j|
				file.puts arr[0].to_s + arr[1].to_s + arr[2].to_s + i.to_s + j.to_s	
			end
		end


	elsif arr[0] != '*' and arr[1] != '*' and arr[2] != '*' and arr[3] == '*' and arr[4] != '*'
		(0..9).each do |i|
			(0..9).each do |j|
				file.puts arr[0].to_s + arr[1].to_s + arr[2].to_s + i.to_s + arr[4].to_s	
			end
		end
	elsif arr[0] != '*' and arr[1] != '*' and arr[2] != '*' and arr[3] != '*' and arr[4] == '*'
		(0..9).each do |i|
				file.puts arr[0].to_s + arr[1].to_s + arr[2].to_s + arr[3].to_s + i.to_s
		end
	elsif arr[0] != '*' and arr[1] != '*' and arr[2] != '*' and arr[3] != '*' and arr[4] != '*'
		raise "Böyle pattern olmaz."

	end
end

=begin
if arr[0] == '*' and arr[1] != '*'
	(0..9).each do |i|
		(0..9).each do |j|
			file.puts i.to_s + arr[1].to_s + arr[2].to_s + j.to_s + arr[5].to_s
		end
	end
elsif arr[1] == '*'
	(0..9).each do |i|
		(0..9).each do |j|
			(0..9).each do |z|
				file.puts i.to_s + arr[specificIndex[0]].to_s + arr[specificIndex[1]].to_s + j.to_s + z.to_s + arr[specificIndex[2]].to_s
			end
		end
	end
elsif arr[2] == '*'
	(0..9).each do |i|
		(0..9).each do |j|
			(0..9).each do |z|
				file.puts i.to_s + arr[specificIndex[0]].to_s + arr[specificIndex[1]].to_s + j.to_s + z.to_s + arr[specificIndex[2]].to_s
			end
		end
	end



end

=begin
elsif "*18**3".



	(0..9).each do |i|
		(0..9).each do |j|
			(0..9).each do |z|
				file.puts arr[specificIndex[0]].to_s + i.to_s + arr[specificIndex[1]].to_s + j.to_s + z.to_s + arr[specificIndex[2]].to_s
			end
		end
	end
end

file.close


=begin





#asteriskIndex.each do |i| 





	(0..9).select |num| do
		if excepting.include? num
			next
		else
			if



			specificIndex.



			file.puts + + + + arr[asteriskIndex[i]] = num
		end
	}

	end 
	

end


mode

A) 
B) basamaklarda bilinen değerler varsa giriniz = 1*33** || ******
C) **	

0)

	******


1)

data
	1*8**3     // TEKRARLANMAYAN

2)

	1*8**3     // TEKRARLANAN

=end