#!/usr/bin/env ruby

=begin
ARGV.length.times do |i|
	if ARGV[i] == "--pattern" or ARGV[i] == "-p"
		pattern = ARGV[i+1]
	elsif ARGV[i] == "--charset" or ARGV[i] == "-c"
		charset = ARGV[i+1]
	elsif ARGV[i] == "--fileName" or ARGV[i] == "-o"
		fileName = ARGV[i+1]
	elsif ARGV[i] == "--help" or ARGV[i] == "-h"
		DictionaryProcesses.helpMenu
	end
end
=end

#puts "tamamdır" if "5" =~ /\A[0-9]\z/
#puts "tamamdır" if "*" =~ /\A[0-9]\z/


excepting = []
specificIndex = []
asteriskIndex = []
count = 0


arr = "*18*3".split('')

=begin
"1*8**3".chars do |c| 
	if c =~ /[0-9]/
		excepting.push(c)  # Tekrarlanmayı önlemek için depolanır.
		specificIndex.push(count)
	else
		asteriskIndex.push(count)	# Yıldızlar tespit edilir.
	end

	count += 1
end
=end


file = File.open("deneme.txt", "w")


if arr[0] == '*' and arr[1] == '*' and arr[2] == '*' and arr[3] == '*' and arr[4] == '*'
elsif arr[0] == '*' and arr[1] == '*' and arr[2] == '*' and arr[3] == '*' and arr[4] != '*'
elsif arr[0] == '*' and arr[1] == '*' and arr[2] == '*' and arr[3] != '*' and arr[4] == '*'
elsif arr[0] == '*' and arr[1] == '*' and arr[2] == '*' and arr[3] != '*' and arr[4] != '*'
elsif arr[0] == '*' and arr[1] == '*' and arr[2] != '*' and arr[3] == '*' and arr[4] == '*'
elsif arr[0] == '*' and arr[1] == '*' and arr[2] != '*' and arr[3] == '*' and arr[4] != '*'
elsif arr[0] == '*' and arr[1] == '*' and arr[2] != '*' and arr[3] != '*' and arr[4] == '*'
elsif arr[0] == '*' and arr[1] == '*' and arr[2] != '*' and arr[3] != '*' and arr[4] == '*'
elsif arr[0] == '*' and arr[1] == '*' and arr[2] != '*' and arr[3] != '*' and arr[4] != '*'
elsif arr[0] == '*' and arr[1] != '*' and arr[2] == '*' and arr[3] == '*' and arr[4] == '*'
elsif arr[0] == '*' and arr[1] == '*' and arr[2] == '*' and arr[3] == '*' and arr[4] != '*'

if arr[0] == '*' and arr[1] != '*'
	(0..9).each do |i|
		(0..9).each do |j|
			file.puts i.to_s + arr[1].to_s + arr[2].to_s + j.to_s + arr[5].to_s
		end
	end
elsif arr[1] == '*'
	(0..9).each do |i|
		(0..9).each do |j|
			(0..9).each do |z|
				file.puts i.to_s + arr[specificIndex[0]].to_s + arr[specificIndex[1]].to_s + j.to_s + z.to_s + arr[specificIndex[2]].to_s
			end
		end
	end
elsif arr[2] == '*'
	(0..9).each do |i|
		(0..9).each do |j|
			(0..9).each do |z|
				file.puts i.to_s + arr[specificIndex[0]].to_s + arr[specificIndex[1]].to_s + j.to_s + z.to_s + arr[specificIndex[2]].to_s
			end
		end
	end



end

=begin
elsif "*18**3".



	(0..9).each do |i|
		(0..9).each do |j|
			(0..9).each do |z|
				file.puts arr[specificIndex[0]].to_s + i.to_s + arr[specificIndex[1]].to_s + j.to_s + z.to_s + arr[specificIndex[2]].to_s
			end
		end
	end
end

file.close


=begin





#asteriskIndex.each do |i| 





	(0..9).select |num| do
		if excepting.include? num
			next
		else
			if



			specificIndex.



			file.puts + + + + arr[asteriskIndex[i]] = num
		end
	}

	end 
	

end


mode

A) 
B) basamaklarda bilinen değerler varsa giriniz = 1*33** || ******
C) **	

0)

	******


1)

data
	1*8**3     // TEKRARLANMAYAN

2)

	1*8**3     // TEKRARLANAN

=end